[package]
name = "auto-error-into"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto-error-into-macro = { version = "0.1.0", path = "../auto-error-into-macro"}
